directory: /media/lepisma/Data/Music
library: /media/lepisma/Data/Music/beets.db
import:
  copy: yes
  write: yes
ui:
  color: yes
  colors:
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: red
    text_highlight_minor: lightgray
    action_default: turquoise
    action: blue
threaded: yes
pluginpath:
  - /media/lepisma/Data/Projects/bbq/beetsplug
  - /media/lepisma/Data/Projects/jove/beetsplug
plugins: >
  chroma discogs fromfilename embedart
  fetchart ftintitle play web jove bbq
  mpdstats mpdupdate bpd smartplaylist
smartplaylist:
  relative_to: /media/lepisma/Data/Music
  playlist_dir: ~/.mpd/playlists
  playlists:
    - name: all.m3u
      query: ""
bbq:
  fields: artist title album
play:
  command: vlc
chroma:
  auto: no
fetchart:
  auto: yes
  maxwidth: 500
embedart:
  remove_art_file: yes
