# Main beets config
directory: /run/media/lepisma/Data/Music
library: /run/media/lepisma/Data/Music/beets.db
import:
  copy: yes
  write: yes
threaded: yes
ui:
  color: yes
  colors:
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: red
    text_highlight_minor: lightgray
    action_default: turquoise
    action: blue

# Plugins and config
plugins: >
  acousticbrainz bbq bpd chroma discogs duplicates edit embedart export fetchart
  fromfilename ftintitle fuzzy info lastgenre lastimport lyrics mbsync mpdstats
  mpdupdate play smartplaylist web
bbq:
  fields: artist title album
chroma:
  auto: no
embedart:
  remove_art_file: yes
fetchart:
  auto: yes
  maxwidth: 500
lastfm:
  user: AbhinavTushar
lastgenre:
  auto: yes
  canonical: yes
  count: 5
lyrics:
  auto: yes
play:
  command: mplayer $args -playlist
smartplaylist:
  relative_to: /run/media/lepisma/Data/Music
  playlist_dir: /run/media/lepisma/Data/Music/Playlists
  playlists:
    - name: all.m3u
      query: ""
